### ISSUE TITLE
Purpose of this repo

### ISSUE THREAD

**Issue by sameo** [kata-containers/kata-containers#1]
@gnawux What is this repo for? Compared to the community and the website one, what does it add?

**Comment by jodh-intel** [comment]
Hi @gnawux - I think I may have suggested we create this site originally. However:

- since https://katacontainers.io/ redirects to https://github.com/kata-containers/community.
- and since we also have https://github.com/kata-containers/documentation
  (for hosting technical documentation common to all the main kata code repositories)

... shall we just delete this repo [*]?

---

[*] - If we *do* want to keep it, I think we need a `README.md` pointing off to the other repositories and explaining why we have this one.

**Comment by gnawux** [comment]
@jodh-intel I am thinking the same thing... 
But I still think we'd better have an *obvious* main repo. Maybe we should delete this one and propose to change the name of the kata-containers/community

**Comment by jodh-intel** [comment]
Hi @gnawux - I'm now starting to think that we do indeed need an obvious "main" repo as you say. I still think we should retain the separate community rep, but I've just thought of some other uses for such a central repo:

- Using it to discuss design decisions that affect `>1` code repository

  For design/architecture-related discussions.

- Using it for tracking changes that we want to apply to all the code repositories

  For process-related tasks.

These two use-cases appear pretty similar on the surface. I've had a need for the 2nd one one a few occasions already (for example ensuring we've applied all the static checks and `go test` script changes to all the code repos). I guess we *could* create separate repos for the use-cases above (`design` / `architecture` and `process`. However, we don't want too many repositories as it'll start to get confusing for everyone ;)

Whatever we decide, I think we need to explain what all the repos are used for "somewhere" so we can point users at the document. I do think that this sort of "table of contents" document that explains the use of each repo probably would make sense to live in this repo.

WDYT @sameo, @grahamwhaley, @klynnrif?
