### ISSUE TITLE
Remove `kata-` prefix from `kata-runtime` sub-commands

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#1011]
There are two sub-commands of `kata-runtime` named with `kata-` prefix:

- `kata-check`
- `kata-env`

And one config option:
- `--kata-config`
- `--kata-show-default-config-paths`

And running `kata-runtime` or `kata-runtime --help` also print this info:

```
NOTES:

- Commands starting "kata-" and options starting "--kata-" are Kata Containers extensions.

```

Since all sub-commands are all Kata's "extensions" after 2.0, there is no need to distinct traditional or Kata command. 

So should we delete these prefix ? 

CC @jodh-intel

**Comment by fidencio** [comment]
@liubin, although I agree that removing the `kata-` prefix would make things cleaner, I'd not sure whether it's the best idea to change a CLI option like that, resulting in incompatible CLI options for 2.0 and 2.1, for instance.

**Comment by jodh-intel** [comment]
# Background

We added the `kata` prefix to "namespace" these commands (and options) from the [OCI mandated command names](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md) and the `runc`-provided commands / options (which occasionally deviated from the OCI spec but which `docker` was relying on).

# Opinion

I agree that now we have removed OCI CLI support we don't need those prefixes but I also agree with @fidencio. Since 2.0 has now been released, I don't think we should potentially break user scripts / workflows by changing the names now.

# Idea

Why not support both for one or two releases? We could deprecate the `kata*` prefix and then remove support for the `kata*` prefixes in, say, release 2.1.x?

# Implementation

fwics the `cli` package supports alternative names for commands so this should be easy to implement:

```go
type Command struct {
    // The name of the command
    Name string
    // A list of aliases for the command
    Aliases []string
```
(from https://godoc.org/github.com/urfave/cli#Command)

We could get clever and display a warning if users use the "deprecated" command name (`kata-check` rather than `check` for example).
