### ISSUE TITLE
CI: Tests failing without the "Not OK" error log

### ISSUE THREAD

**Issue by AdithyaKrishnan** [kata-containers/kata-containers#10451]
The AMD SNP Nightly CI is failing on certain tests but we're unable to get the complete error log. 
Earlier, each failure would display a "Not OK <test number>" message in the log but we are no longer able to find such error messages in the log. 

However, there is a final error message at the end of the test run.

Example run:
https://github.com/kata-containers/kata-containers/actions/runs/11470553718/job/31920643716

Final Error Message:
ERROR: Tests FAILED from suites: k8s-guest-pull-image-encrypted.bats k8s-guest-pull-image-authenticated.bats k8s-guest-pull-image-signature.bats k8s-confidential-attestation.bats

**Comment by stevenhorsman** [comment]
As discussed on the CI call we are getting "Executed 2 instead of expected 3 tests" which in the past we've seen if there is a syntax error in the test, but that doesn't seem to be the case here.

**Comment by stevenhorsman** [comment]
I've tried bumping bats to 1.10 in https://github.com/kata-containers/kata-containers/pull/10459 and in a sample size of 1 the non-tee tests are passing. There is a high chance it could be chance though.

**Comment by danmihai1** [comment]
@stevenhorsman @AdithyaKrishnan @fidencio , my debug messages from https://github.com/kata-containers/kata-containers/pull/10478/files suggest that a good next step would be to replace the "trap EXIT" commands from confidential_kbs.sh.   

bats-core issue 364 and its friends suggest that using trap inside a bats test is non-trivial.

Maybe one you understands better than me the intended flow of the KBS tests and volunteers to replace these traps? I was afraid to experiment in this area because of the risk of leaking or otherwise disturbing the KBS set-up.

Looks like we currently skip teardown for failed tests and the failing tests get reported as passing:

```2024-10-31T20:02:12.6910290Z [run_kubernetes_tests.sh:136] INFO: Executing k8s-guest-pull-image-signature.bats
2024-10-31T20:02:12.7628228Z 1..5
2024-10-31T20:02:13.0673018Z [bats-exec-test:14] UNBUFFERED: INFO: test 1: setup starting
2024-10-31T20:02:13.4929606Z [bats-exec-test:34] UNBUFFERED: INFO: test 1: setup succeeded
**2024-10-31T20:02:13.4975365Z [bats-exec-test:82] UNBUFFERED: INFO: test 1: starting
<<<<<<<- missing teardown for failing test
2024-10-31T20:04:16.0595711Z [bats-exec-test:14] UNBUFFERED: INFO: test 2: setup starting**
2024-10-31T20:04:17.7749658Z [bats-exec-test:34] UNBUFFERED: INFO: test 2: setup succeeded
**2024-10-31T20:04:17.7802074Z [bats-exec-test:99] UNBUFFERED: INFO: test 2: starting
2024-10-31T20:04:45.6444694Z [bats-exec-test:132] UNBUFFERED: INFO: log doesn't contain: Security validate failed: Validate image failed: Cannot pull manifest
<<<<<<<- missing teardown for failing test
2024-10-31T20:04:45.7216909Z [bats-exec-test:14] UNBUFFERED: INFO: test 3: setup starting**
2024-10-31T20:04:46.8531601Z [bats-exec-test:34] UNBUFFERED: INFO: test 3: setup succeeded
2024-10-31T20:04:46.8580169Z [bats-exec-test:116] UNBUFFERED: INFO: test 3: starting
...
```

**Comment by AdithyaKrishnan** [comment]
Closing thanks to merger of PR#[10459 ](https://github.com/kata-containers/kata-containers/pull/10459)
