### ISSUE TITLE
Docker no longer detects Kata Containers v2 after its installation

### ISSUE THREAD

**Issue by didier-durand** [kata-containers/kata-containers#1123]
Hi there,

# Description of problem

This is most probably related to #1122

With Kata V1, Docker install (coming after Kata's) would detect the presence of kata-runtime and include it as an available runtime. With install of v2 via snap, it is no longer the case: see the 2 `docker info` below to compare for both versions.

# Expected result

Continue to make kata-runtime visible to docker as a possible runtime. It becomes default in with v1 but that's not necessary.

# Actual result

## Docker info with Kata v2

ddurand@microk8s-kata:~$ sudo docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 _**Runtimes: runc
 Default Runtime: runc**_
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: 
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1029-gcp
 Operating System: Ubuntu Core 16
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 14.65GiB
 Name: microk8s-kata
 ID: OLEV:RJSU:XETW:NU3Y:MWUQ:Z2WX:GHVE:MJIY:HTQK:GUF7:AFN6:DTDU
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

# Further information

## Docker info with Kata v1

ddurand@microk8s-kata:~$ sudo docker info

Client:
Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 _**Runtimes: kata-runtime runc
 Default Runtime: kata-runtime**_
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: N/A
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1029-gcp
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 14.65GiB
 Name: microk8s-kata
 ID: 4L6R:M6BD:NR66:QNFD:YHIL:JMUY:EL46:GQY6:7YHA:B6WM:AQ7T:CDDT
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 22
  Goroutines: 36
  System Time: 2020-11-16T01:19:50.385044278Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by jodh-intel** [comment]
Hi @didier-durand - unfortunately, newer versions of Kata (2.x+) don't currently work with docker since docker doesn't yet support the newer shimv2 architecture used by Kata. See https://github.com/kata-containers/runtime/issues/3038.

**Comment by jodh-intel** [comment]
@didier-durand - That's why the Kata 2.x installation docs (https://github.com/kata-containers/kata-containers/tree/2.0-dev/docs/install#packaged-installation-methods and specifically https://github.com/kata-containers/kata-containers/blob/2.0-dev/utils/README.md) mention Kata 2.x + containerd rather than Kata 2.x + Docker.

**Comment by didier-durand** [comment]
@jodh-intel: thanks for this info that I missed in the doc! Any idea if there is a chance for support by Docker? Any timeline?

**Comment by jodh-intel** [comment]
@amshinde may have some thoughts on this.

**Comment by didier-durand** [comment]
The reason why I am asking is that Docker is currently much more widely spread than containerd.  
I have built a nice showcase for [MicroK8s + Docker + Kata V1 ](https://github.com/didier-durand/microk8s-kata-containers): I guess that I will have to wait a bit to move it to V2 even though I will try the mininal containerd install proposed by [the page](https://github.com/kata-containers/kata-containers/blob/2.0-dev/utils/README.md) that you referred me to.

**Comment by fidencio** [comment]
@didier-durand, I'm closing this one as we'll be tracking the re-addition (or not) of the OCI CLI commands as part o the issue #722.  Please, feel free to subscribe to that issue for getting updates on this.

**Comment by didier-durand** [comment]
@fidencio : Ok. I subscribed to #722. Thanks for the explanations. Didier

**Comment by struanb** [comment]
I'm sharing the following in case it's helpful to anyone who, like us, needed VM isolation for their container workloads, a virtiofs-based solution (ruling out Kata v1) and compatibility with `docker run` or `podman run` (ruling out Kata v2).

Due to issues like this one, experienced using Docker/Podman CLI to launch Kata Containers, we built [RunCVM](https://github.com/newsnowlabs/runcvm) (Run Container VM): an experimental open-source Docker container runtime, for launching standard container workloads in VMs.

Please note that RunCVM is not a direct competitor to Kata: as an experimental runtime, RunCVM cannot offer the same levels of stability and support as Kata. However RunCVM _may_ be suitable for some use cases and _is compatible_ with `docker run` today (with experimental support for `podman run`). Like Kata v2, RunCVM is also virtiofs-based for speed. RunCVM has minimal system dependencies: it relies on the Linux KVM module, and can even be installed in a [GitHub Codespace](https://codespaces.new/newsnowlabs/runcvm).
