### ISSUE TITLE
Runtime tracing should reuse Trace() in katautils

### ISSUE THREAD

**Issue by cmaf** [kata-containers/kata-containers#1162]
There are several similar trace() functions in virtcontainers and containerd-shim-v2 (as of #2980) that create spans and set tags for the span. We can reuse Trace() in pkg/katautils/tracing.go if we modify it to take tag keys and values as arguments.

Forward port of https://github.com/kata-containers/runtime/issues/3093

**Comment by fidencio** [comment]
I'm removing the "needs-review" label of the issue, as it's a valid one and is already tagged with the correct "area/*" label.

**Comment by cmaf** [comment]
1.x PR: https://github.com/kata-containers/runtime/pull/3100

@bporter816, this PR unfortunately didn't make it into 1.x but would be extremely useful as a 2.0 contribution and we plan on porting it. There have been significant changes to tracing since the initial patch so there will need to be changes to [#3100](https://github.com/kata-containers/runtime/pull/3100).

Are you able to/would you like to port and submit it to the kata-containers/kata-containers repo?

**Comment by bporter816** [comment]
@cmaf Sure, I can look into porting this. Are #1352 and #1389 still the only major changes to be aware of?

**Comment by cmaf** [comment]
@bporter816 those are the main ones, and there are additional ones where some tracing code was removed like in https://github.com/kata-containers/kata-containers/pull/1749 and where syntax and variable names were changed in https://github.com/kata-containers/kata-containers/pull/1539 and https://github.com/kata-containers/kata-containers/pull/1551 to fix static checks (not an exhaustive list)

**Comment by bporter816** [comment]
@cmaf 
On the last PR, we decided to pass the individual loggers into the single trace function, like so: https://github.com/bporter816/runtime/blob/consolidate_tracing/pkg/katautils/katatrace/tracing.go#L105
Do we still want to do that here, or could we use the kata utils logger for all the "trace called before context set" errors?

**Comment by cmaf** [comment]
@bporter816, if we can pass the loggers in for now, let's do that so we can preserve some logging information from the calling function

**Comment by bporter816** [comment]
@cmaf @jodh-intel 
Should the goal here be to completely remove any case in which opentelemetry is being imported outside of the tracing package? Wondering about this since there are many cases where a trace span is created, then after that call, dynamic data is passed in with additional tags, resulting in the need to import and use the `label` package to declare the tags - example in https://github.com/kata-containers/kata-containers/blob/1faaf5f35dc6bfb0e7ebf1ec55f8cf6627f15cdd/src/runtime/pkg/katautils/create.go#L162

One idea I thought of is I could add a function to the tracing package `AddTag(span otelTrace.Span, key string, value string)` that makes this generic key/value strings and pulls out the opentelemetry dependency...but that doesn't really help since the span needs to be passed in, which is also an opentelemetry dependency.

Is it fine to leave lines such as the above example unchanged, only passing in the static tags to the trace function?

**Comment by cmaf** [comment]
> Should the goal here be to completely remove any case in which opentelemetry is being imported outside of the tracing package? 

It would be nice but not necessary for now IMO; the goal is to reuse `Trace()`

> One idea I thought of is I could add a function to the tracing package `AddTag(span otelTrace.Span, key string, value string)` that makes this generic key/value strings and pulls out the opentelemetry dependency. 

It would be great to add a function like that! If you have time, please do. Otherwise I or someone else can add this later.

> It's worth noting that in newer versions of opentelemetry, the `label` package has been moved to `attribute`, so as things are now this import path will need to be updated everywhere it's used (14 places in the codebase) if the opentelemetry version is bumped.

Yeah we'll need to update the OpenTelemetry version & import path and having to update it in fewer places is preferable (but not strictly necessary for this issue).

/cc @jodh-intel @liubin

**Comment by bporter816** [comment]
@cmaf I opened a PR for this. Looking at testing it with the test script to make sure the span created message still works.
