### ISSUE TITLE
Bump containerd library to 1.5.0

### ISSUE THREAD

**Issue by zhsj** [kata-containers/kata-containers#1441]
**Which feature do you think can be improved?**

I'm planing to package kata-runtime for Debian. As Debian is much stricter on the library vendor policy, I want to de-vendor as much as possible of the libraries. Usaually Fedora has the same policy, but I find the Fedora package of kata-runtime is not strictly following the policy.

The first thing is kata-runtime uses many ancient libraries. For example the github.com/containerd/containerd is v1.2.1-0.20181210191522-f05672357f56, which is more than 2 years old.

I plan to bump the library versions. This issue is only for github.com/containerd/containerd.

Since github.com/containerd/containerd 1.5.0 (only released beta.1 recently) has merged the cri code, and is the first version that adopts Go modules. I suggest to move 1.5.0 directly, instead of the stable version 1.4.3.

github.com/containerd/containerd has bumped github.com/opencontainers/runc to v1.0.0-rc93, but runc has a large refactor of the libcontainer package. So I plan to stick runc on an old version with replace in go.mod. And bump runc later.

**How can it be improved?**

Describe how specifically you think it could be improved.

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by fidencio** [comment]
Let me also /cc @c3d and @etrunko, who are the Fedora maintainers of the Kata Containers' packages.

I quick look pointed out that Fedora already has a big chunk of the golang-* packages, and not so many would have to be added in order to have the package not relying on the vendored code (but rather on Fedora packages).

Mind, I'm not sure whether there's the wish / it's worth it to do that on the Fedora side, it's up to the maintainers, but it's worth tor raise the issue. :-)
