### ISSUE TITLE
kata containers repo consolidation

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#172]
As we have discussed during AC meeting, we wanted to consolidate the (currently scattered) kata code repositories. The issue serves as a meta tracker for such change.

Possibly targets:
* move all code and documentation repositories into kata-containers repo
* move ci repo into the tests repo

Current status:

- [x] runtime
- [x] agent
- [x] documentation
- [x] osbuilder
- [x] packaging

/cc @amshinde

**Comment by chavafg** [comment]
Opened PRs for this:
#192 that merges the runtime repo and 
#194 that merges proxy and shim repos. 


Taking @jodh-intel comments from https://github.com/kata-containers/ci/issues/260#issuecomment-605869696, 

do we want to merge the next ones:

- documentation - There is an effort ongoing by @mvincerx and team to fix some issues in our doc repo, so maybe we should wait a little bit and then merge? also @mvincerx may give us some guidance on what the new documentation structure should be in this repo. 

- osbuilder - I see a comment from @jodh-intel saying: `Can't decide if this should be moved or kept stand-alone`, @jodh-intel can you elaborate more on this? 

- agent - Are we planning to have the go agent as part of kata 2.0? 

- tests and ci - we have agreed to merge this later on. 

/cc @kata-containers/architecture-committee 
/cc @amshinde @jcvenegas @bergwolf

**Comment by bergwolf** [comment]
@chavafg I think we need to re-sync on which repositories are going in here. As part of kata 2.0 goal, we would like to:
1. make `rust-agent` the default agent and abandon go-agent 
2. drop kata-runtime command line support

If we agree on above two goals, `runtime` is the only **code** repository that needs to be merged here. Maybe we need AC's consensus on this? I thought we have but it doesn't hurt to ask for clarification. @kata-containers/architecture-committee 

Also w.r.t. other repositories, 
- documentation - I agree we can wait a bit for the on-going modification to settle down, as long as it doesn't block `kata-containers` testing.

- osbuiler - I would say just merge it.

- packaging - I would say just merge it.

- agent - let's drop it and enhance the rust-agent to fill any gap we see there.

- proxy/shim - let's drop them as part of dropping command line support

**Comment by jodh-intel** [comment]
@chavafg - my thoughts:

- osbuilder: on reflection I think we should just merge it here.

- packaging: agreed - let's just merge it here.

- documentation: We may actually want to merge this now since it contains docs like the developer guide. We can then get to work on removing all non-Kata 2.0 content. The same applies to the architecture guide. We'd also get the stable branch versions of the docs "for free". But maybe @mvincerx wants to comment on this.

- agent: That was my understanding too - we'd standardise on the rust agent hence we don't need the golang agent in this repo. Even if we don't standardise on it, we already have "an agent" in this repo so it's unclear where we'd put the existing golang one. Hence, if we don't standardise on the new rust agent, I'd say we should just build the golang agent from the existing stand-alone repo and package as required. Again, if the packaging is in this repo, we're not going to impact (aka break) the 1.x.y releases.

- runtime cli support (+proxy/shim import): I think we should get the AC team to agree to this as it's a significant change. It  also impacts being able to run Kata "stand-alone" (https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#running-standalone). That's been an important feature for debugging, as a learning tool, and as a framework to write tests for. At the very least, we should document (in this repo) how to continue to work with "pure Kata" (or as simple a setup as possible, without the addition of a container manager, blah).

- tests: If we *don't* merge that repo here, how are we going to for example disable the tests for the runtime CLI (assuming we delete that part of the runtime in this repo)? Wouldn't it be simpler to merge tests and have it only operate on the content of this repo (meaning we can just delete all the tests that no longer apply in the copy of tests we put here)?

Clearly, once we've merged the repos there will be a lot of tidy-up / rework to do. I've just noticed that if we assume a rust agent and merging osbuilder, we can simplify osbuilder by removing the `RUST_AGENT=no` logic along with the alpine and euleros support I think?

**Comment by mvincerx** [comment]
> * documentation - There is an effort ongoing by @mvincerx and team to fix some issues in our doc repo, so maybe we should wait a little bit and then merge? also @mvincerx may give us some guidance on what the new documentation structure should be in this repo.

Thanks for asking @chavafg and @jodh-intel. Fundamentally, I think the question we have to ask is: How do we make it easy for folks to contribute to our docs? I arrived late to this party, so I don't understand the rationale for including the documentation repo inside `kata-containers` main repo.
I recommend keeping the documentation repo as is.  

**warning**: tl;dr

Am I missing anything you've already discussed? As an open source contributor, I'd find it easier to simply fork and clone the documentation repo, set up the GOPATH variable for validation, and start working on branches. On the other hand, if the documentation repo were included inside the kata-containers repo, I'd be forced to accept unnecessary overhead (unless I'm missing something previously discussed. Correct my understanding if so. )

In working with @jodh-intel, I proposed simplifying the presentation of the kata containers project by **pinning only the kata-containers repo** on the  [kata-containers GitHub page](https://github.com/kata-containers), like we did in the [Clear Linux Project Github page](https://github.com/clearlinux). 

IMHO, we should consider two major entry points where our contributors arrive:
- https://katacontainers.io/
- https://github.com/kata-containers

I have a proposal to simplify these user paths and can share on request.  We have to make it easier for folks to contribute. A major part of that is simplifying anticipated user paths. (SEO strategy is a separate issue.)

Example: There's a `CONTRIBUTING.md`  in the `kata-containers` main repo, which is a landing page to go to the real `CONTRIBUTING.md`  in the `community`  repo. We can eliminate this extra step by simplifying content in the `README.md` at the `kata-containers` main repo.

**Comment by jodh-intel** [comment]
Hi @mvincerx - agreed, we need to keep the overhead low for new contributors. I think there may be ways to do this even if we do merge the `documentation` repo into this one though. It's hinted at on https://github.com/kata-containers/kata-containers/issues/195 and elsewhere, but we could essentially have different levels of ovhead depending on (one or both of these):

- Different sub-directories in this repo
- Different filetyes

For example, we *could* consider "lowering the bar" for minor documentation changes by filtering on whether the PR is changing a "`*.md`" file. We might decide for example to not mandate a "Fixes: #XXX" comment as that's an extra step that generally catches out new contributors.

**Comment by mvincerx** [comment]
Hey @jodh-intel. Thanks for your response. I'm open to including `documentation` into the `kata-containers` repo; I just want to assure that doing so doesn't raise the bar for PRs to pass CI. 
I'm wondering if we might also be able to relax acceptance in the static checks if the `docs:` subsystem prefix appears in the PR.  Let's discuss this and your "conventional commmits" proposal, per GH-195, in our next meeting.

**Comment by bergwolf** [comment]
All of runtime, agent, documentation, osbuilder and packaging have been merged. Let's close this one.
