### ISSUE TITLE
Support "docker run --shm-size <bytes>"

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#21]
This Docker `--shm-size` option is not honoured.

**Comment by amshinde** [comment]
Since this value is not passed in the OCI spec file, we need to inspect the shm mount on the host side that docker creates for us. Looking at this, I think one way to do this is search for the mount in /proc/mounts,  parse the mount options there to get the "size=" mount option and then pass this to the agent. 

What do you think @jodh-intel @grahamwhaley @sboeuf ?

**Comment by grahamwhaley** [comment]
Yep, I think the current theory is we'd have to look on the host and pass it into the guest. tbh though, I'm not exactly sure what happens when you pass `--shm-size` to docker - so first we should ascertain that by investigation. For instance, I don't know if it makes a host system wide change, or if it only affects the `/dev/shm` mount point in the namespace of the container?
We should also understand if all `/dev/shm` mounts are shared across all containers or not - have a look at that `--proc` run argument. That might affect our decision I suspect.

The, I think `/proc/mounts' will not give you the size of the mount - I think (after a quick surf) that you will need to use `getmntent(3)` most likely (or see if there is a golang lib equiv etc.)

**Comment by amshinde** [comment]
@grahamwhaley In case of docker, docker sets up shared memory for the container under /var/lib/containers/{containerid}/shm and mounts it. This is passed as a bind mount in the spec file, the runtime is supposed to bind mount this to /dev/shm within the container, which is what runc does. In our case, passing this tmpfs from the host to the guest does not make sense.

I have not looked at how this is handled in CRI/k8s. It makes sense to have a shared shm mount among containers in a pod, but then again I havent looked at this.
@egernst @sboeuf Do you know how this is handled?

Regarding the `/proc/mounts file`, it does give us the mount options  including the size used  by docker for mounting the container specific shm mount. I think with `getmntent` you get all the parsing done for you, but you still need to specify a mount file to look at.

**Comment by sboeuf** [comment]
This can be split into 2 parts:
- Identify the `shm` size (maybe using `/proc/mounts` as suggested by @amshinde )
- Test the case of CRI and identify what is the expectation between containers of the same pod regarding shared memory. Investigation results might lead us to implement a mechanism storing the `shm` path to identify if the same shared memory needs to be reused by another container of the pod. This means we would not create a new shared memory for the container in this case, but instead, we would point to the existing one.

**Comment by amshinde** [comment]
I took a closer look at this recently.

- For the first part, one can get the shm size using statfs  and use this for setting up the shm mount. With this, Docker `--shm-size` option can easily be supported.

- For the CRI case, both `cri-o` and `cri-containerd` setup a sandbox level `shm` mount  in case `-ipc` is not set to host.
The other containers then bind-mount this sandbox-level `shm` mount. In case `ipc` is set to host, the host `/dev/shm` is used. We cannot really support this case where `ipc` is shared with the host.

Currently, we do not the `shm` mount as a bind mount but change this to a `tmpfs` mount before passing this to the agent, so that it is not passed through 9pfs.  
https://github.com/kata-containers/runtime/blob/9fb0b337ef997079b304fe895dacd5d96d6f2fb6/virtcontainers/kata_agent.go#L617-L622

But we do create a separate `shm` mount for every container in a pod.

This looks like another case where we cannot support the OCI spec. My proposal is to pass the `shm-size` as part of the `CreateSandbox` request and delete all shm mounts from the OCI spec that we pass to the agent. The agent would then setup a shared `shm` mount using the size passed to it while creating the sandbox, and every container would then bind mount this shared `shm` mount.

@bergwolf @sboeuf What do you think?

**Comment by bergwolf** [comment]
@amshinde I like your proposal. We stick to the sandbox level shared IPC namespaces.

**Comment by sboeuf** [comment]
That's sounds pretty good, but I am not sure about implementation details here. This sounds to me a lot like the PID namespace thing where you had to move things to the `CreateContainer` step. Otherwise, you don't have this information when creating the sandbox itself, right ?

**Comment by amshinde** [comment]
@sboeuf This is more like the shared IPC namespace where this is a given that the IPC namespace needs to be shared unlike the PID namespace. My approach here is that it is a given that `shm` needs to be shared.

**Comment by amshinde** [comment]
I see that cri-o sends an annotation called "io.kubernetes.cri-o.ShmPath" containing the shared shm path. Might be useful to have this added for cri-containerd as well.

**Comment by sboeuf** [comment]
@amshinde, sure but don't you need to know about shm size when you create it ?
In this case, you don't have the size info when calling into CreateSandbox()

**Comment by amshinde** [comment]
Yes my approach was based on the fact that we get an annotation about the shm path.  I realized that we get this from cri-o, but not with cri plugin on testing this. We could have this added to crr-containerd plugin so that we know the shared shm path at the time the sandbox is created.

Without this, a feasible alternative is to pass the shm mount as a new storage for the sandbox container along the lines of: 
Storage{Driver:"shm", fstype:"tmpfs", MountPoint: "sandbox-shm-path"}

And then modify the OCI shm mounts for all containers to bind mount this sandbox mount.

**Comment by sboeuf** [comment]
Yes sounds like a good approach. And as discussed offline, you'll have to figure out if the `shm` path should be decided inside the virtcontainers to be passed to the agent, or if the agent should simply define a new shm, and any new container will bind mount the same if they get a boolean telling them to do so.
Your approach might be the most appropriate because it means that we will modify the OCI spec appropriately from virtcontainers, leaving less special cases to handle into the agent.
