### ISSUE TITLE
Backports Guideline

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#2429]
Currently we have issues in doing backports in tests and kata-containers repository, this issue is affecting our release process as most of the times takes a lot of time to figure out CI issues and which things should be part of the release of the stable branches and which are not.  Even if we do the merge of the test repository here at the kata-containers repository, I am sure that the backporting will be still a problem. I believe that in order to make easier to the author of the PRs to determine if his or her PR should be backport or not we should create a general list of the things that we currently do a backport. I believe that even this list will help to the PR reviewers to have a general idea if the PR that they are reviewing should or not be backport, this will help to the reviewer to ask to the author of the PR to raise the proper backport of his or her PR. I believe that in case that someone detects that a certain PR needs a backport. Currently, we have labels but I see that those most of the time are not use or if they are use the author of the PRs do not the proper backports. 
Wdyt?
/cc @amshinde @bergwolf @chavafg @fidencio @Jakob-Naucke @jcvenegas @egernst @jodh-intel

**Comment by fidencio** [comment]
First of all, @GabyCT, thanks a whole lot for raising this issue, I'll add comment through the day Tomorrow (I need a clear mind to go through this with the attention it deserves).

**Comment by fidencio** [comment]
> /cc @marcel-apf @snir911 @devimc @eadamsintel @lifupan @liubin

**Comment by snir911** [comment]
+1
AFAICT many commits which seems to be no-backport-needed PRs became a requirement later on as other backport-needed PRs appears to silently rely on them and I afraid there're many other similar hidden scenarios, having said that, it's indeed would be helpful to have such guidelines and labeled PRs (and having the backport PR along with the PR would be even better :))

Would it be possible to make the needs-backport/no-backport-needed a requirement for a PR to be merged?

**Comment by Jakob-Naucke** [comment]
> I believe that in order to make easier to the author of the PRs to determine if his or her PR should be backport or not we should create a general list of the things that we currently do a backport.

@GabyCT I agree we should improve the process and make backporting less of a guesswork. Do you think a list would be more powerful than just filtering by labels?

> Would it be possible to make the needs-backport/no-backport-needed a requirement for a PR to be merged?

@snir911 We had this requirement I think in the v2.0 days, I believe it meant "needs backport to v1.x" at the time.
If we do this, I think there should also be a "backport done" label, which would make project management easier.
One thing that would be very nice (but I don't know whether GitHub's tooling would support this) is making it possible for non-member PR authors to apply these labels. This annoyed me back then, as I wasn't a member and would usually write something like "no backport needed" in the PR message and some dear PR scrubber (often @GabyCT :)) would add the label, which I find a bit clumsy.

**Comment by wainersm** [comment]
I agree with @GabyCT 's proposal, we should have accurate, up-to-date and better backports guidelines.

Other than that, we could have some automation in place.

(Hereafter I  start to brainstorm...)

For example:

1. When the PR is opened, do:

1.1 If any "Fixes" points to a issue of *Bug* type then automatically label it as "backport-candidate". There are flaws: a) developer forgot to add the "Fixes"  b) mixing in commits for fixes and enhancements c) some commits without "Fixes"
1.2 Any internal contributor should be able to manually label it too
1.3 A PR for enhancement won't be labeled; to ensure the PR was inspected then maybe it could be posted a message like "It seems to not need backport"

2. A PR with "backport-candidate" is blocked until a reviewer or developer remove the "backport-candidate" label  (meaning no backport is needed) or replace it with "backport-stable-x.y".

3. Configure one of [those bots](https://github.com/marketplace?type=&verification=&query=backport+) to automatically generate the backport from the PRs labeled with "backport-stable-x.y"
3.1. Ideally configure the bot to generate the backport PR only and only after all checks (including CI) had passed, so to avoid unnecessary complexity in the process 

4. The merger (usually a reviewer) will have to merge both PRs, ideally at same pass. Maybe the bot won't be able to simply cherry-pick commits due to conflicts. The merger (alongside the developer) should resolve any merge conflict as well as the CI passes on both PRs.

Talk is cheap, I know I know :)

**Comment by GabyCT** [comment]
Closing this issue
