### ISSUE TITLE
 unified single config option for enabling debugging

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#246]
As being discussed in the PTG, one of the complaints from developers is that it is too complex to enable kata's debug config. Instead of having to change `enable_debug` for each components, we can add a global one for ease of use.

**Comment by jodh-intel** [comment]
Could you share some further details on this request @bergwolf? Currently, we provide one debug option per component (roughtly) in the config file. That allows fine-grained debugging to be enabled. But if you want to "just enable debug", you run a single command to set all the debug options on:

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug

That information is *slightly* stale in the sense that you no longer need to modify the `kernel_params`. So, to enable full debug, you could minimally just run a single command, which doesn't seem that complex (?):

```sh
$ sudo sed -i -e 's/^# *\(enable_debug\).*=.*$/\1 = true/g'  "$config_file"
```

If we're going to create a top-level `enable_debug` option, we'd need a new stanza in the config file. I guess something like the following:

```toml
[kata]
enable_debug = true
```

I do wonder if we could consider reworking the config for v2 to use YAML since that supports structured options like this in a better way than TOML does (imho).
