### ISSUE TITLE
snap build fails at qemu on ppc64le

### ISSUE THREAD

**Issue by Amulyam24** [kata-containers/kata-containers#3002]
```
/usr/bin/ld: cannot find -ludev                                                                                                              
collect2: error: ld returned 1 exit status  
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:156: run-ninja] Error 1
make: *** [GNUmakefile:11: all] Error 2
```

**Comment by gkurz** [comment]
> ```
> /usr/bin/ld: cannot find -ludev                                                                                                              
> collect2: error: ld returned 1 exit status  
> ninja: build stopped: subcommand failed.
> make[1]: *** [Makefile:156: run-ninja] Error 1
> make: *** [GNUmakefile:11: all] Error 2
> ```

Hi !

Please provide the full log for this build. A variety of reasons could lead to /usr/bin/ld not finding libudev.

**Comment by Amulyam24** [comment]
Hi @gkurz , the steps to reproduce this on ppc64le would be:
```
cd $GOPATH/go/src/github.com/kata-containers/kata-containers/
sudo snapcraft -d snap --destructive-mode
```

Full log of qemu build - [qemu.log](https://github.com/kata-containers/kata-containers/files/7553565/qemu.log)

**Comment by gkurz** [comment]
> Hi @gkurz , the steps to reproduce this on ppc64le would be:
> 
> ```
> cd $GOPATH/go/src/github.com/kata-containers/kata-containers/
> sudo snapcraft -d snap --destructive-mode
> ```
> 
> Full log of qemu build - [qemu.log](https://github.com/kata-containers/kata-containers/files/7553565/qemu.log)

So this log has :

```
WARNING: Static library 'udev' not found for dependency 'libudev', may not be statically linked
Run-time dependency libudev found: YES 245
```

which indicates that libudev-dev is installed but as said in https://github.com/kata-containers/kata-containers/pull/3003#issuecomment-970473200 the static library isn't shipped. This causes the linking error.

I reproduce exactly the same with a freshly installed ubuntu 20.04.3 on x86_64 if I install libudev-dev.

So this isn't a question of arch, it is just that you cannot build a static QEMU with libudev under ubuntu,
and most other distros as well, since they don't have the libudev.a. The correct fix is to disable libudev
when building static as suggested in https://github.com/kata-containers/kata-containers/pull/3003#pullrequestreview-805086454 .
