### ISSUE TITLE
Update node.k8s.io/v1beta1 to node.k8s.io/v1

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#3185]
Related: https://github.com/kata-containers/tests/pull/4244

```bash
$ grep -rn "node.k8s.io/v1beta1" .
./tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml:3:apiVersion: node.k8s.io/v1beta1
./tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml:16:apiVersion: node.k8s.io/v1beta1
./tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml:29:apiVersion: node.k8s.io/v1beta1
./docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md:157:apiVersion: node.k8s.io/v1beta1
```

**Comment by fidencio** [comment]
Please, whoever will work on this, pretty please, mind: https://kubernetes.io/releases/.

If something is deprecated in v1.21+, we can only drop it when v1.20 reaches its EOL (which should happen in 2022-02-08).
If something is deprecated in v1.22+, we can only drop it when v1.21 reaches its EOL (which should happen in 2022-06-28).

**Comment by fidencio** [comment]
Is my understanding https://github.com/kata-containers/kata-containers/pull/3188#issuecomment-985498653 correct?
If so, what's the way to go about this?  I would not like to have something that can still work with a maintained version of k8s to stop working just because we want to use a new API (without providing a backwards compatible solution, if needed).

**Comment by fidencio** [comment]
Okay, for RuntimeClass, from https://kubernetes.io/docs/concepts/containers/runtime-class/
```
Runtime Class
FEATURE STATE: Kubernetes v1.20 [stable]
```
