### ISSUE TITLE
Failed to create containerd task: failed to create shim: open /dev/vhost-vsock: no such device: unknown

### ISSUE THREAD

**Issue by n30gupta** [kata-containers/kata-containers#3459]
Hi all,

I am having my running kubernetes custer on bare metal and I have successfully installed kata-deploy through daemon sets and also runtimeclass but when I am trying to create a pod by using Qemu as a runtime class I am getting below error:
**failed to create containerd task: failed to create shim: open /dev/vhost-vsock: no such device: unknown**
Can anyone help me to resolve this issue. If any more information is required do let me know.

Regards
Nikhil Gupta

**Comment by devimc** [comment]
have you tried `sudo modprobe vhost-vsock` ?

**Comment by n30gupta** [comment]
@devimc  I have run the cmd as suggested by you it is showing below error:
root@ubuntuserver:~# sudo modprobe vhost-vsock
modprobe: ERROR: could not insert 'vhost_vsock': Device or resource busy

**Comment by n30gupta** [comment]
@devimc How i can insert or install that module into my system

**Comment by devimc** [comment]
@n30gupta try rebooting your system or using https://www.freedesktop.org/software/systemd/man/systemd-modules-load.service.html

**Comment by n30gupta** [comment]
@devimc  when I run kata-runtime kata-check on my vm it is showing below error:
root@ubuntuserver:~# kata-runtime kata-check
WARN[0000] Not running network checks as super user      arch=amd64 name=kata-runtime pid=2616835 source=runtime
ERRO[0000] CPU property not found                        arch=amd64 description="Virtualization support" name=vmx pid=2616835 source=runtime type=flag
WARN[0000] modprobe insert module failed                 arch=amd64 error="exit status 1" module=vhost_vsock name=kata-runtime output="modprobe: ERROR: could not insert 'vhost_vsock': Device or resource busy\n" pid=2616835 source=runtime
ERRO[0000] kernel property not found                     arch=amd64 description="Host Support for Linux VM Sockets" name=vhost_vsock pid=2616835 source=runtime type=module
WARN[0000] modprobe insert module failed                 arch=amd64 error="exit status 1" module=kvm_intel name=kata-runtime output="modprobe: ERROR: could not insert 'kvm_intel': Operation not supported\n" pid=2616835 source=runtime
ERRO[0000] kernel property not found                     arch=amd64 description="Intel KVM" name=kvm_intel pid=2616835 source=runtime type=module
ERRO[0000] ERROR: System is not capable of running Kata Containers  arch=amd64 name=kata-runtime pid=2616835 source=runtime
ERROR: System is not capable of running Kata Containers

**Comment by devimc** [comment]
@n30gupta  looks like your system doesn't support kvm, check in the BIOS if virtualization is enabled and try again inserting the module manually `modprobe kvm_intel`

**Comment by yaoyinnan** [comment]
@n30gupta Hello, I also encountered this problem and solved it with the following solution.

The problem may be because vmw_vsock_virtio_transport_common and vmw_vsock_vmci_transport conflict with the vsock and vhost-vsock devices, so just disable them.
```
vim /etc/modprobe.d/blacklist-vmware.conf
blacklist vmw_vsock_virtio_transport_common
blacklist vmw_vsock_vmci_transport
```
The vhost-vsock can then be added using ```sudo modprobe vhost-vsock``` .

Although I don't know if it will solve your problem, but you can try this way.

**Comment by n30gupta** [comment]
@yaoyinnan Thanks for your suggestion but I tried with your steps but I am getting below error:
root@ubuntuserver:~# modprobe vhost-vsock
modprobe: ERROR: could not insert 'vhost_vsock': Device or resource busy
root@ubuntuserver:~#
Any idea on this?

**Comment by yaoyinnan** [comment]
@n30gupta I feel like you can use ```vim``` to look at the file ```/etc/modprobe.d/blacklist-vmware.conf``` to make sure ```blacklist vmw_vsock_virtio_transport_common 
blacklist vmw_vsock_vmci_transport``` is written. Then restart the virtual machine.

After restarting the virtual machine, you can use the command ```lsmod | grep vsock``` to view the ```vsock``` device. Normally there should be no information output. Then try adding the device using ```modprobe vhost-vsock```.

**Comment by n30gupta** [comment]
@yaoyinnan Thanks for sharing the steps it works for me and now I can able to run kata-container on my system, but one query as I am using both runc and kata container as a OCI run time engine and I created kata-qemu as a runtime class and using as a runtime class in YAML definition while deploying sample nginx application. 
How I can verify whether the deployed nginx pod is deployed with runtime as kata container or not? Any lead on this?
And do you have any document or data prepared where I can see the use or comparison of kata container with normal container.

Thanks

**Comment by yaoyinnan** [comment]
@n30gupta You can use the command ```crictl pods``` to look status of pods. The last column shows the container runtime engine.
```
root@Kata:/# crictl pods
POD ID              CREATED             STATE               NAME                   NAMESPACE           ATTEMPT             RUNTIME
a46565c85d17c       21 seconds ago      Ready               busybox-sandbox        default             1                   kata
ea041690bf447       48 seconds ago      Ready               busybox-sandbox-runc   default             1                   runc
```

**Comment by n30gupta** [comment]
@yaoyinnan Thanks for this command I can see my pods using kata-qemu as a runtime.
any document or information you have where I can see the comparison of kata container with normal container.

**Comment by yaoyinnan** [comment]
@n30gupta I don't know if you need a comparison of usage methods or a comparison of performance, security, functions, limitations, etc., but I can share some materials I have read for your reference.

For usage, you can refer to https://github.com/kata-containers/kata-containers/tree/main/docs/how-to.

For the comparison of the latter items, I have read some papers, but not the latest version of runc and kata. You can read these papers:
````
[1] Randazzo A, Tinnirello I. Kata containers: An emerging architecture for enabling mec services in fast and secure way[C]//2019 Sixth International Conference on Internet of Things: Systems, Management and Security (IOTSMS). IEEE, 2019 : 209-214.
[2] Flauzac O, Mauhourat F, Nolot F. A review of native container security for running applications[J]. Procedia Computer Science, 2020, 175: 157-164.
[3] Yang J, Tak B. Security Assessment Technique of a Container Runtime Using System Call Weights[J]. Journal of the Korea Society of Computer and Information, 2020, 25(9): 21-29.
````

I will also share with you if I have new data and documentation.

**Comment by n30gupta** [comment]
@yaoyinnan Thanks for this information , actually I am wondering how I can find or see the difference using kata containers or normal containers , I am in exploring phase of kata containers , I am searching for any use case where I can see the difference and decide which one I will use in implementation whether the kata container or normal container.

Thanks!

**Comment by yaoyinnan** [comment]
@n30gupta My understanding is that kata uses a virtual machine to provide additional container isolation relative to runc. In terms of security, it provides defense against container escape problems. In terms of performance, it provides solutions to problems such as fault isolation, resource preemption, and performance interference. In multi-tenant scenarios, it can better prevent untrusted applications and deal with resource allocation issues.

I feel to think you may be interested in the following questions:

1. For what reasons do you need to use a hybrid container runtime instead of using all of the Kata container runtimes?
My understanding is as follows: For scenarios with high-security requirements, such as finance, kata containers can be used in full or at a higher rate. For multi-tenant scenarios, since there are applications with untrusted tenants, kata can be used in full to provide isolation. For containers that provide external service API, there is a risk of container escape after being penetrated by attackers, and kata can also be used to providers isolation. For some scenarios with low-security requirements, kata and runc can be mixed.
2. When mixing, what factors determine the use of kata?
My understanding is as follows: some long life cycle pods can use kata to avoid malicious container escape behavior. However, pods with a short life cycle have higher performance requirements, and because of their short life cycle, attackers have high attack costs, so runc can be used.

The above content is my personal understanding, and if I have more knowledge in the future, I will also share it with you. At present, I have no data to support the above content, and if there is more data to support it, I will share it with you.

**Comment by cmaf** [comment]
@n30gupta since the initial issue was resolved, I am closing this issue. Feel free to reopen if necessary or create another issue.
