### ISSUE TITLE
Calling virtiofsd without 'announce-submounts' could lead to inode number collision

### ISSUE THREAD

**Issue by germag** [kata-containers/kata-containers#3507]
Kata mounts different filesystems in a shared directory, and it is possible two files end up having the same inode number. 
In this case, some tools like `find` will not work properly.

Enabling `announce-submounts` in `virtiofsd` will prevent this situation.

**Comment by rhvgoyal** [comment]
I think it is a good idea for kata containers to enable "-o announce_submounts" and see how does it go. There are some pros and cons. In the end pros might outweigh cons.

Pros:
- If multiple filesystems are mounted in shared dir, there is a possibility of inode number conflict inside guest/container. announce submounts solves that problem because it reports a different device number if it encounters a submount.
- Now syncfs() support is being added to virtiofsd. It will work faster with announce_submounts because it will sync only one filesystem in that case. Without it, it will try to issue syncfs() on all the submounts it knows about.

Cons:
- Some people are concerned that it exposes the host's view of mounts inside guest. I am not too concerned about it. But if this is a concern for somebody, then don't use announce_submount. This has just been raised a theoretical concern only so far.
- It is a new option. So once we start using it, there might be some issues which we can look into.

Overall, I would think that it probably is a good idea to give "-o announce_submounts" a try.

**Comment by rhvgoyal** [comment]
cc @XanClic

**Comment by fidencio** [comment]
> "It is a new option"

When was this introduced, @rhvgoyal?  I think we'd need to properly treat the cases where we enable it, depending on the version, which could impact on enabling it by default.

**Comment by rhvgoyal** [comment]
> > "It is a new option"
> 
> When was this introduced, @rhvgoyal? I think we'd need to properly treat the cases where we enable it, depending on the version, which could impact on enabling it by default.

In C version of virtiofsd it was introduced in Sept, 2020. Following is upstream commit.

commit 08dce386e77eb9ab044cb118e5391dc9ae11c5a8
Author: Hanna Reitz <hreitz@redhat.com>
Date:   Wed Sep 9 20:40:26 2020 +0200

    virtiofsd: Announce sub-mount points

So it is little more than a year old. 

I would say evaluate it and see if it works reasonably well to be used as default option.

**Comment by Jakob-Naucke** [comment]
> When was this introduced, @rhvgoyal? I think we'd need to properly treat the cases where we enable it, depending on the version, which could impact on enabling it by default.

@fidencio this might not be a big deal with our recent mandate of 6.1.0 (#3552), is it?

**Comment by fidencio** [comment]
As @Jakob-Naucke  pointed out, with us requiring QEMU 6.1.0 that's perfectly fine to get in as soon as a PR is raised.
@germag, please, go ahead with the patch and I will review it in a timely manner.
