### ISSUE TITLE
CC | osbuild: Integrate pause image into the Kata rootfs image

### ISSUE THREAD

**Issue by arronwy** [kata-containers/kata-containers#4768]
For CoCo stack, the pause image is managed by host side, then it may configure a malicious pause image, we need package an pause image inside the rootfs and don't the pause image from host.

The reasons we don't pull the pause image inside the guest, one is performance, another is the trusted storage for CoCo is not ready when launch the pause container https://github.com/confidential-containers/documentation/issues/39

**Comment by yoheiueda** [comment]
@arronwy Thank you very much for preparing PR #4769. 

The PR has been merged. Are you planning to submit further PRs to make kata-agent use the embedded pause container image? 

Do we need to update the custom containerd for CC to enable the embedded pause image?

**Comment by arronwy** [comment]
> @arronwy Thank you very much for preparing PR #4769.
> 
> The PR has been merged. Are you planning to submit further PRs to make kata-agent use the embedded pause container image?
> 
> Do we need to update the custom containerd for CC to enable the embedded pause image?

Hi @yoheiueda , one commits in this PR: https://github.com/kata-containers/kata-containers/pull/4885/commits will use embedded pause image for containers defined in pod yaml file, the pause container managed by containerd for sandbox will need changes at containerd part, @wllenyj may can help on this part.

**Comment by yoheiueda** [comment]
@arronwy thank you for the info.

I checked the code in the commit, and understand that `PullImage` is required to be called before `CreateContainer` for a pause container, since the content of the embedded pause container image must be copied to `/run/kata-containers/<cid>/rootfs` beforehand, so the custom containerd also needs to send `PullImage` for the integrated pause container image to fix https://github.com/kata-containers/kata-containers/issues/4477.
