### ISSUE TITLE
CC | agent: Allow the aa_kbc_params to be passed through in the command line

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#5178]
**Which feature do you think can be improved?**

Currently the only way to select and pick between the different kbc options is using the `aa_kbc_params` parameter in the kata agent config.toml file, which is 'baked into' the rootfs. This means that if a user wanted to switch between KBC (or stop using one at all), or update their KBS URI they'd need to rebuild the kata guest image, which isn't that simple.

**How can it be improved?**

If we allowed the option to be passed through the kata-container's configuration's kernel_params field with a new  `agent.aa_kbc_params` parameter, this would enable us to make those changes just from the host side without having to rebuild the image.

I think this is probably required for any remote attestation scenario we want to support in the first release, e.g. with EAA, but I don't know if that is in scope.
I'm not 100% sure how the interaction with the offline SEV KBC and the simple KBS works. I think it is remote attestation, but it gets the URI and config via other fields in the kata-containers config (e.g. `guest_pre_attestation_proxy`), but @ryansavino & @fitzthum can correct me and/or confirm.

**Additional Information**

The kernel_params passed from the command line are measured, so I thought that this would be fine from a trust model point of view, but @fitzthum has mentioned that:
> The kbc parameter actually isn't trusted so really we should find a way to pass it such that it doesn't change the measurement.

Unfortunately I don't know enough about the measurement and what should be in the TCB to understand if there are big issues with this approach. I naively thought that if we updated the config to talk to a different remote KBC URI we'd want to have that as part of the measurement, but it seems this assumption isn't correct, so we might want to take a different approach.

**Comment by fitzthum** [comment]
> I'm not 100% sure how the interaction with the offline SEV KBC and the simple KBS works. I think it is remote attestation, but it gets the URI and config via other fields in the kata-containers config (e.g. guest_pre_attestation_proxy), but @ryansavino & @fitzthum can correct me and/or confirm.

For the first release we are using the `offline_sev_kbc`, which is remote attestation via `simple_kbs` but it's offline attestation, meaning that there is no persistent communication between the guest and the kbs. Basically we just inject some secrets at boot and then the KBC reads them. So the `offline_sev_kbc` doesn't have any special parameters. It's the shim that communicates with the KBS. 

We also have an `online_sev_kbc` that is already working and merged, but we haven't tested it much so it's not going to be used for the first release. This does use a KBS URI set via the `aa_kbc_params`. The online kbc is required for signature support btw (because the signature stuff is too big to directly inject). 

> Unfortunately I don't know enough about the measurement and what should be in the TCB to understand if there are big issues with this approach. I naively thought that if we updated the config to talk to a different remote KBC URI we'd want to have that as part of the measurement, but it seems this assumption isn't correct, so we might want to take a different approach.

Very reasonable assumption, but the way Ive been thinking about it is that 1) measuring the KBS_URI doesn't guarantee much because the CSP controls the network and could probably reroute things if they really wanted to. 2) The KBS_URI is probably going to change a lot and it would be a pain if it caused the measurement to change every time. 3) The consequences of using the wrong KBS are minimal. It will just mean that the secrets won't get delivered. 

Now the KBS_URI and AA_KBC_PARAMS aren't quite the same. Right now I don't think any of the KBCs do anything sensitive with the KBC params, but we'll need to keep an eye out. Not trusting the params does have some risk, but I think it is optimal. 


So really I don't think adding the params as a kernel module would do any harm, because it should be basically the same as it is now, but idk if it's essential for release 1. 

I think there are two potential reasons we might do it. First, it makes it easier to change the KBS_URI when the KBS moves around. Like I said, this doesn't matter for SEV currently, but it does for TDX. I think the long term solution here is to provide a non-measured config pathway. See this issue I made in kata a while ago https://github.com/kata-containers/kata-containers/issues/4541

Second, adding the kernel param might make the initrd more generic. Currently even if we don't use the `KBS_URI` with SEV, we do set a particular KBC. Maybe with a kernel param we could converge the initrd. One of our big goals is to have a generic guest image. Of course one of our bigger goals is to have a generic guest measurement, so the issue above will probably be the best longterm solution again. 

So all that is to say I don't really care either way. Could be useful to add the param now, but I think something slightly different would be better in the long run.

**Comment by stevenhorsman** [comment]
Thanks for that Tobin, that's really great background and helps me understand more of the scope. I definitely agree that have a generic image is ideal, which is way I'm trying to come up with some things that let us pass config in without updating it, but as you say, we need to factor in the measurement and make sure that we don't compromise usability in one area for pain somewhere else!

**Comment by fitzthum** [comment]
Ok, we are in the process of switching to the online kbc for SEV, which relies on the `aa_kbc_params` to get the URI of the KBS. I'm realizing that we really don't want to set this URI as part of the bundle building process (when we setup the agent config file). So I think this is actually a higher priority than I first realized. 

I think the longterm solution is still to have some kind of unmeasured configuration, but it would be handy to have this in the short term. 

@Alex-Carter01

**Comment by arronwy** [comment]
> Ok, we are in the process of switching to the online kbc for SEV, which relies on the `aa_kbc_params` to get the URI of the KBS. I'm realizing that we really don't want to set this URI as part of the bundle building process (when we setup the agent config file). So I think this is actually a higher priority than I first realized.
> 
> I think the longterm solution is still to have some kind of unmeasured configuration, but it would be handy to have this in the short term.
> 
> @Alex-Carter01
> 
> btw @arronwy i think you will run into the same problem when you try to add the EAA tests.

Yes, fully agree.

**Comment by anakrish** [comment]
@fitzthum 
> 1) measuring the KBS_URI doesn't guarantee much because the CSP controls the network and could probably reroute things if they really wanted to. 
> 2) The KBS_URI is probably going to change a lot and it would be a pain if it caused the measurement to change every time.
> 3) The consequences of using the wrong KBS are minimal.

I'm trying to understand the design. In image-rs, the `security policy` is fetched from KBS.
https://github.com/confidential-containers/image-rs/blob/60bfcfa86011355362992f91bdd92da75e75eec6/signature/src/agent.rs#L117-L120

Would not measuring the KBS_URI allow an untrusted KBS to supply an arbitrary security policy that would allow a malicious container to be run, that could mimic the kata-agent stack?

**Comment by anakrish** [comment]
Thanks for the explanation, @fitzthum. Looking forward to the blog post. 

Does it mean that only encrypted images can be run with kata-cc?

**Comment by fitzthum** [comment]
> Does it mean that only encrypted images can be run with kata-cc?

No, you can do a signed image but there should be a secret involved in your workload somewhere. For instance you could have a signed image that uses credentials it gets from the Attestation Agent (workloads can query the attestation agent via gRPC) to connect to a database and download some secrets. Hypothetically most workloads that uses CC will have some kind of secret so it shouldn't be too disruptive.

**Comment by anakrish** [comment]
@fitzthum Could you shed some light on the following in case you blog post is not yet ready?

> You might think we could put the public key in the host data, but there are actually some more subtle reasons why this won't really work.

**Comment by stevenhorsman** [comment]
I think this issue was closed with PR #5533, so I'm closing it, but if there is anything outstanding then feel free to re-open it and list what I've missed. Thanks!
