### ISSUE TITLE
containerd-shim-kata-v2 list not working

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#541]
With kata-runtime 1.x, we have the following option
```
$ kata-runtime list
ID          PID         STATUS      BUNDLE      CREATED     OWNER
```
however, it seems that for 2.x, that is not working
```
$ containerd-shim-kata-v2 list
io.containerd.kata.v2: shim namespace cannot be empty
```

or 
```
$ kata-runtime list
Invalid command "list"
```
any idea if this feature is going to be enabled ?
/cc @jodh-intel @bergwolf

**Comment by liubin** [comment]
How about using `ctr` or `crictl`?

**Comment by jodh-intel** [comment]
Hi @GabyCT - this is expected since we removed the OCI CLI commands as 2.0 was planned to only support shim v2. However, docker and podman haven't caught up yet :-)

We plan to re-add the CLI commands to allow continued use of those container managers (see https://github.com/kata-containers/kata-containers/issues/722).
