### ISSUE TITLE
[forward port]: kata-deploy: add ACRN runtime to Docker configuration

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#579]
Port https://github.com/kata-containers/packaging/pull/1077 (issue https://github.com/kata-containers/packaging/issues/1078) from Kata 1.x.

**Comment by jodh-intel** [comment]
Hi @gvancuts - would you be able to look at this?

**Comment by gvancuts** [comment]
Sure. Do I understand correctly that the ask is to add it to the `2.0-dev` branch in this repo?

(PS: looks like I messed up the issue number that is fixed by this patch, it was meant to fix this issue: https://github.com/kata-containers/packaging/issues/1078 ... probably too late to correct this now... :-()

**Comment by jodh-intel** [comment]
Hi @gvancuts - yes, that's right - I think this should also be applied to 2.0-dev.

Yes, unfortunately, we can't change the issue number now, but np, it's not a "biggie" :smile:

**Comment by gvancuts** [comment]
Sounds good, I'll get this done!

**Comment by gvancuts** [comment]
> Sounds good, I'll get this done!

Just did this, PTAL
