### ISSUE TITLE
kernel building: Add module unload to SEV kernel config

### ISSUE THREAD

**Issue by Alex-Carter01** [kata-containers/kata-containers#5866]
Need to add to the sev kernel config for use of the efi secret kernel module.

adding module unloading, otherwise `modprobe -r efi_secret` will error

@dubek

**Comment by wainersm** [comment]
Hi @Alex-Carter01 , allow me to check I understood the problem:

 * it affects `offline_sev_kbc` only
 * it is the attestation-agent that will load the EFI secret module
 * and the atttestation agent cannot load because  "The module should be available but not loaded before KBC is invoked. The KBC will not be able to unload the module if /proc has not been mounted." (https://github.com/confidential-containers/attestation-agent/blob/main/src/kbc_modules/offline_sev_kbc/README.md)

**Comment by fitzthum** [comment]
This affects both online and offline KBS. Loading the EFI Secret module extracts secrets from memory and puts them into the filesystem. For the offline KBS these secrets consist of everything needed to run the pod (i.e. all the keys for all the containers). For the online KBS the secret is a key that is used to setup a persistent connection with the KBS. 

The attestation agent is in charge of loading and unloading the module. It expects to do both. The secrets are wiped from the fs and memory when the module is unloaded. If the kernel is built without support for unloading modules the KBC will break.

**Comment by wainersm** [comment]
> This affects both online and offline KBS. Loading the EFI Secret module extracts secrets from memory and puts them into the filesystem. For the offline KBS these secrets consist of everything needed to run the pod (i.e. all the keys for all the containers). For the online KBS the secret is a key that is used to setup a persistent connection with the KBS.
> 
> The attestation agent is in charge of loading and unloading the module. It expects to do both. The secrets are wiped from the fs and memory when the module is unloaded. If the kernel is built without support for unloading modules the KBC will break.

Thanks for the write up. I finally took some time to learn those topics and that kind of write up help a lot. Thanks @fitzthum !
