### ISSUE TITLE
[forward port]: virtcontainers: Add to bridges unit test

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#602]
Port https://github.com/kata-containers/runtime/pull/2828 (issue https://github.com/kata-containers/runtime/issues/2827) from Kata 1.x.

**Comment by jodh-intel** [comment]
fwics @cmaf you are the most careful porter atm! (congrats :trophy: :smile:) But this one may have slipped through :)

**Comment by cmaf** [comment]
@jodh-intel haha, this one was ported already! https://github.com/kata-containers/kata-containers/pull/423 😄 

I will double check that the changes between the two are consistent next week before suggesting closing this though.

**Comment by cmaf** [comment]
@jodh-intel, I checked and this is ported. #423 (issue https://github.com/kata-containers/kata-containers/issues/422).

There is a comment on both PRs about the porting. Are there additional steps I need to take in order to close this? didn't see a label I could apply to indicate it is ported, are we adding one?
