### ISSUE TITLE
How to cross compile kata-container for arm64 in x86 platform?

### ISSUE THREAD

**Issue by Maxppddcsz** [kata-containers/kata-containers#6405]

**Comment by jongwu** [comment]
Hi @Maxppddcsz -, out of curious, is there any scenarial to cross build kata? What does your arm machine looks like?

**Comment by XiangyiXuWashU** [comment]
The arm machine is QEMU emulated ARM v8.4 with S-EL2 extension(max CPU in QEMU) in x86 machine. We do that because there is no commercial development kit for that. Therefore, we hope that kata could be cross compiled, and copy executable aarch64 file to emulated arms machine. The reason why we don't build in QEMU emulated ARM is that the speed is too slow.

**Comment by jongwu** [comment]
Hi @XiangyiXuWashU -,
I'm not sure if you can run kata inside a VM. It just like nested virtualization which generally refers to 2 levels of hardware asistant virtualization however in your case the first level of virtualization is pure sofeware emulation. That's interesting, I have not tried for that. You can very if kata can run inside your VM firstly by run a qemu-kvm VM in side your arm VM.

As for cross-build kata, I have not tried that either. There a lots of commonents for kata, we need try them one by one. I'll try it if I have time. It's an interesting topic I think.

**Comment by jongwu** [comment]
Hello @XiangyiXuWashU @Maxppddcsz -, I open a PR to enable cross build kata, see https://github.com/kata-containers/kata-containers/pull/6586

**Comment by fidencio** [comment]
Our latesst pre-release contains the arm64 artefacts: https://github.com/kata-containers/kata-containers/releases/tag/3.2.0-alpha3

I'm closing the issue, feel free to re-open if if you think it's needed.
