### ISSUE TITLE
runtime-rs: ch: Implement pause/resume VM

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#6434]
Implement the following methods in https://github.com/kata-containers/kata-containers/blob/main/src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs:

- `pause_vm()`
- `resume_vm()`

**Comment by cmaf** [comment]
Pause and resume are already implemented in the agent for pausing and resuming a task, so all that needs to be done for runtime-rs is updating the container status to paused or running. We don't want to pause the VM because then the runtime can't communicate with the agent. See previous discussion in https://github.com/kata-containers/runtime/issues/317, https://github.com/kata-containers/runtime/pull/328

@amshinde @jodh-intel
