### ISSUE TITLE
snp: add snp support for kata-shim (main)

### ISSUE THREAD

**Issue by ryansavino** [kata-containers/kata-containers#6576]
@fitzthum
@niteeshkd

**Comment by fidencio** [comment]
I am assuming this one was covered by the PRs that got merged from @fitzthum and @UnmeshDeodhar, and based on that I'm closing the issue.  If this is not the case, please, just re-open it and sorry for the noise.

**Comment by fitzthum** [comment]
@stevenhorsman I think this should still be open as well.

**Comment by katexochen** [comment]
Can someone summarize what is missing here?

**Comment by fitzthum** [comment]
> Can someone summarize what is missing here?

SNP generally works already but there are a few things to iron out and a couple things needed for attestation.

For example, we need to switch to the AMDSEV firmware package to be able to use measured-direct-boot so that we can actually measure the full TCB. Niteesh has a PR for this, but it has been stalled due to CI issues.

We also need to update the shim to pass in the cert chain via the QEMU command line. I think Niteesh is also working on that.

There are a few other even smaller things.

cc @ryansavino @niteeshkd @AdithyaKrishnan

**Comment by wainersm** [comment]
Hi @fitzthum !

I think this is fully implemented at this point. right? If yes, can we close it?
