### ISSUE TITLE
getting started with docker, use Kata-runtime

### ISSUE THREAD

**Issue by hubbertsmith** [kata-containers/kata-containers#6851]
**Which feature do you think can be improved?**

objective: set up docker to use kata-runtime

need to modify docker daemon.json
if docker was installed using snap -- /var/snap/docker/current/config/daemon.json
if docker was installed using apt -- /etc/docker  ... /daemon.json
add logic to the daemon.json file >>> this is just an example (I'm not sure it works, I can help testing), restart docker
{
    "runtimes": {
        "kata": {
            "path": "/usr/bin/kata-runtime"
        }
    },
    "default-runtime": "kata",
    "experimental": true
}

snap restart docker

**Comment by fidencio** [comment]
So, I'm not exactly sure how to configure docker to use Kata Containers via its json file, but here's what I did in order to test whether it is working or not (spoiler alert, it's not): https://github.com/kata-containers/kata-containers/issues/6861#issue-1713532882

We've regressed on that front, and we'll find some time to get it fixed.
