### ISSUE TITLE
runtime-rs: device manager block index incorrect

### ISSUE THREAD

**Issue by cmaf** [kata-containers/kata-containers#7119]
In device_manager.rs, block index is set to 1 which generally corresponds to vdb per the notes in the code. Is there a reason for choosing this over 0/vda?

@jodh-intel could you describe the problem you were seeing with this?

**Comment by jodh-intel** [comment]
I noticed this odd behaviour working on the Cloud Hypervisor runtime-rs code. When I run containerd with devmapper like this...

```bash
$ sudo ctr run --runtime "io.containerd.kata.v2" --snapshotter devmapper --rm -t "quay.io/prometheus/busybox:latest" foo sh
```

... the runtime-rs device manager constructs a `SharedInfo` object with `index=1`. That gets converted into a `BlockConfig` object that contains guest-side device `/dev/vdb` like this:

```
BlockConfig { path_on_host: "/dev/dm-1", is_readonly: false, index: 1, driver_option: "blk", virt_path: "/dev/vdb", ... }
```

runtime-rs then calls the hypervisors `add_device()` method passing these details. But this is the _first_ block device so when we convert the request into a Cloud Hypervisor block device add request, it creates `/dev/vda`, not `/dev/vdb`.

This subsequently causes the agent to fail since runtime-rs make an `CreateContainer` agent API call containing `/dev/vdb` in the `Storage` message. But that device doesn't exist in the guest: only `/dev/vda` does.
