### ISSUE TITLE
tests: Add tests for measured rootfs integrity checking

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#7245]
With PR https://github.com/kata-containers/kata-containers/pull/6756 merged into main, support for integrity checking was added, so we now need to add some CI tests for this feature. We have a couple of tests for this in `CCV0` for both [kuberentes](https://github.com/kata-containers/tests/blob/087f2d01c2d4125927b27a60310f1d9115d1b96e/integration/kubernetes/confidential/agent_image.bats#L110-L125) and [containerd/crictl](https://github.com/kata-containers/tests/blob/087f2d01c2d4125927b27a60310f1d9115d1b96e/integration/containerd/confidential/agent_image.bats#L15-L32), but they are fairly tightly coupled with the other CC tests, so need refactoring. It's also the strategic direction to add new tests to GHA, running on AKS, rather than to the tests repo, so I think this is an opportunity to do that refactoring.

Questions
- How do we get a build of kata with `MEASURED_ROOTFS` enabled for the kernel, shim and rootfs?
- Should we add containerd via crictl tests as well as Kubernetes tests? Does the GHA framework support these yet?
- What other platforms do we want to support for these tests? s390x, TDX etc?

## Acceptance Criteria

For each supported platform:

_**Scenario: Check correct hash works**_
**Given** I have a version of kata installed that has a kernel with the initramfs built and config with `rootfs_verity.scheme=dm-verity rootfs_verity.hash=<correct hash of rootfs>` set in the `kernel_params`
**When** I try and create a container a basic pod
**Then** The pod is successfully created

_**Scenario: Check incorrect hash fails**_
**Given** I have a version of kata installed that has a kernel with the initramfs built and config with `rootfs_verity.scheme=dm-verity rootfs_verity.hash=<incorrect hash of rootfs>` set in the `kernel_params`
**When** I try and create a container a basic pod 
**Then** The pod is doesn't run
  **And** Ideally we'd get a helpful message to indicate why

**Comment by fidencio** [comment]
@stevenhorsman, thanks for creating the issue.

> * How do we get a build of kata with `MEASURED_ROOTFS` enabled for the kernel, shim and rootfs?

It'd be easy, and can be done following what we have for CCv0.
We'd need to adapt the `kata-deploy-binaries.sh` script, and then update the GitHub actions to do that.

> * Should we add containerd via crictl tests as well as Kubernetes tests? Does the GHA framework support these yet?

As part of CCv0 we rely on k8s for testing this, and we could simply do the same here.
About `ctr` tests, those are not yet supported with our GHA, and I'm working on setting up a GARM machine that can give us runners where we can start executing these tests, but it's a work in progress now as there's more pressing things on the horizon.

> * What other platforms do we want to support for these tests? s390x, TDX etc?

s390x, TDX, and vanilla.

**Comment by wainersm** [comment]
> @stevenhorsman, thanks for creating the issue.
> 
> > * How do we get a build of kata with `MEASURED_ROOTFS` enabled for the kernel, shim and rootfs?
> 
> It'd be easy, and can be done following what we have for CCv0. We'd need to adapt the `kata-deploy-binaries.sh` script, and then update the GitHub actions to do that.
>

I'm afraid I am going to hijack this issue so let me know if you prefer to split on a new issue. Disclaimer: I confess I wasn't following @fidencio 's new Github based CI so closely lately, so I might be making some wrong comments based on inaccurate assumptions below. Anyway, here it goes...  

On CCv0 (the Jenkins CI actually) is more flexible on regarding the CI jobs possibilities than the actual Github CI:
 * `$CI_JOB` defines a job type that encompass and ties together the build configuration, test suites, test environment and platform. E.g. CI_JOB=`CC_SEV_CRI_CONTAINERD_K8S` means `build configuration == (SEV, QEMU,...) AND test suite == (SEV k8s) AND test environment (k8s, containerd) AND platform (SEV)`
 * The variables to build the build configuration and test environment are sourced from `tests/.ci/ci_job_flags.sh`, based on `$CI_JOB`
    * The build configuration and test environment are built by the `.ci/setup.sh ` script. That takes care of different OSes
    * Some test suite also change the test environment (e.g. CoCo tests will configure containerd) 
 * The test suites are executed by `tests/.ci/run.sh`, again based on `$CI_JOB`
   * The suites are distributed in hierarchies that more or less  mimics the $CI_JOB:
      * `integration/containerd/confidential` - crictl with containerd tests (no k8s). Ran by jobs like `CC_CRI_CONTAINERD`
      * `integration/kubernetes/confidential` - k8s tests for non-TEE. Ran by jobs like `CC_CRI_CONTAINERD_k8s`
      * `integration/kubernetes/confidential/sev.bats` - k8s tests for SEV
      * `integration/kubernetes` - simply the original non-CoCo k8s tests
      * etc etc etc
 * Finally the platform is  determined by the machine that the Jenkins job run, so we have multiple jobs

Currently, to the best of my knowledge, the Github jobs on `main` don't have such as flexibility. Essentially we have got jobs per platform only. I'm not saying that we should copy old CI style, actually I really appreciate that the new approach fix some design mistakes (e.g. do not build kata over and over again). I just want to avoid that the new CI grows ad-hoc and spaghetti because we didn't take a pause to discuss a little bit how it can accommodate CI jobs variations. On the other hand I am not advocating to endless "where is the code?" discussions. :)      

Example, I am not sure changing the `kata-deploy-binaries.sh` to accommodate the measured rootfs is correct. The way that I see `kata-deploy-binaries.sh`, it is a builder of tarballs inside container. It calls the component specific builders which live in `tools/packaging/static-build` (each component, kernel, hypervisor..etc...has its own builder). Some external entity should be in charging of aggregating the components that will be part of the "measured boot installation for vanilla kernel", "measured boot installation for TDX", etc. IIUC this "external entity" responsibility is split on many build jobs and the `tests/integration/gha-run.sh` that install the kata-deploy, and we install the same payload to all the jobs.

Ok, the last phrase I was mostly thinking aloud :)

> > * Should we add containerd via crictl tests as well as Kubernetes tests? Does the GHA framework support these yet?
> 
> As part of CCv0 we rely on k8s for testing this, and we could simply do the same here. About `ctr` tests, those are not yet supported with our GHA, and I'm working on setting up a GARM machine that can give us runners where we can start executing these tests, but it's a work in progress now as there's more pressing things on the horizon.
> 
> > * What other platforms do we want to support for these tests? s390x, TDX etc?
> 
> s390x, TDX, and vanilla.

**Comment by wainersm** [comment]
@stevenhorsman keep this and #7415 open?
