### ISSUE TITLE
Non-stop emails about release 3.2.0-alpha4

### ISSUE THREAD

**Issue by remram44** [kata-containers/kata-containers#7512]
# Description of problem

I just got a 4th email from GitHub about release `3.2.0-alpha4`. I don't know if there's something wrong with your build process that keeps rebuilding it over and over, or if they were supposed to be separate tags but somehow are not getting incremented.

# Expected result

One release per version number, each release with its own number.

# Actual result

3.2.0-alpha4 email at 2023-07-31 11:36, again at 2023-07-31 12:34, again at 2023-07-31 20:57, again at 2023-08-01 05:59

# Further information

I've been running the 3.2 alpha releases on my cluster since 3.1 does not work, no idea when or what to install next.

**Comment by fidencio** [comment]
@remram44, sorry for the emails going to you, it happened as we've been facing some issues with the release process, as that ended up broke due to changes in the GitHub actions.

We'll cut a `rc0`  release soon enough, and you can use it.

Also, please, if you'd be happy to help, we can always have more brains and hands to help to avoid such situations in the future.,

Please, if the explanation is "good enough", close the issue.  If not, let us know what's still missing.

**Comment by remram44** [comment]
If it's not a bug then I guess this can be closed. I look forward for the release candidate!

**Comment by fidencio** [comment]
@remram44, https://github.com/kata-containers/kata-containers/releases/tag/3.2.0-rc0 has been released Today.

Please, feel free to give it a trt!
