### ISSUE TITLE
rust agent cgroups crate ftbfs on ARM

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#770]
Seen on Jenkins ARM CI for https://github.com/kata-containers/kata-containers/pull/735 (http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/305/console):

```sh
   Compiling cgroups v0.1.1-alpha.0 (https://github.com/kata-containers/cgroups-rs?tag=0.1.1#3852d7c1)
error[E0308]: mismatched types
   --> /home/jenkins/.cargo/git/checkouts/cgroups-rs-1340950e7d819bfb/3852d7c/src/lib.rs:769:34
    |
769 |     let _ = unsafe { libc::rmdir(p.as_ptr() as *const i8) };
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `cgroups`.
```

/cc @lifupan, @jongwu, @justin-he

**Comment by gnawux** [comment]
@jodh-intel Are you a DD? I missed abbreviations like "FTBFS" for a long time since I hadn't played with Debian.

**Comment by Kvasscn** [comment]
A related issue: https://github.com/kata-containers/cgroups-rs/issues/9

**Comment by jongwu** [comment]
@jodh-intel @Kvasscn maybe I find the root cause. the parameter of libc:rmdir can be i8 in x86 and u8 in aarch64.
the definition of rmdir see  https://github.com/cloud-hypervisor/cloud-hypervisor/blob/7c346c38448a8486353266b23c32273fa4884667/Cargo.toml#L18
The self-defined type c_char can be different type varying with arch, os and lib. see https://github.com/rust-lang/libc/search?p=3&q=pub+type+c_char+%3D.
So I think that it is a bug from cgroup-rs. Maybe we should set different type depending on arch in the definition of libc_rmdir.
see https://github.com/kata-containers/cgroups-rs/blob/8717524f2c95aacd30768b6f0f7d7f2fddef5cac/src/lib.rs#L769
WDYT?

**Comment by jodh-intel** [comment]
@gnawux - alas, no :) I was a DM for a few packages but also used to work with doko, so fbtfs was mentioned a lot around him ;)

@jongwu - nice work! @lifupan - could you tal at this and update https://github.com/kata-containers/cgroups-rs maybe?

**Comment by lifupan** [comment]
Hi @jodh-intel  @jongwu 

Yeah, the root cause was just as jongwu said, there was difference between x86 and aarch64 on c_char's definition. And the PR https://github.com/kata-containers/cgroups-rs/pull/10 had fixed, I'll send a PR to update the cgroup-rs crate in agent to fix it.

**Comment by jodh-intel** [comment]
Thanks @lifupan!

**Comment by Amulyam24** [comment]
FYI, this error is encountered on ppc64le as well. Thanks @jodh-intel, @jongwu and @lifupan for fixing it.
