### ISSUE TITLE
CC: Optimise container creation on guest, by integrate pause image into Kata rootfs image

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#8104]
From https://github.com/kata-containers/kata-containers/issues/4768:
> For CoCo stack, the pause image is managed by host side, then it may configure a malicious pause image, we need package an pause image inside the rootfs and don't use the pause image from host.
>
> The reasons we don't pull the pause image inside the guest is performance

## Things to note/include with this work
- This has a dependency on the basic image pull: https://github.com/kata-containers/kata-containers/issues/8103, after this it can be done in any order I believe.
- I think this is largely based of pieces of the following commits:
  - https://github.com/kata-containers/kata-containers/pull/4769/commits/75b9f3fa3caaae62f49b4733f65cbab0cc87dbee
  - https://github.com/kata-containers/kata-containers/commit/e777860a0c999c269be1c6fbf589c1e957804067
  - The skopeo versions addition from https://github.com/kata-containers/kata-containers/commit/13f6418c46c65764eba2fda4e8a33d62c5ac852b
  - Version update from https://github.com/kata-containers/kata-containers/commit/1bfbeee1dd1aa202f80ea922c192eff88ff637b8
  - image_rpc.rs changes based on https://github.com/kata-containers/kata-containers/commit/ad4a811c39d9a708e17d64350486e4356803d789
  but it's important to note that much of these changes have been updated since they were originally created, so it's probably safest to copy the newest version from `CCv0`, but remembering to add the original authors in the commit

## Questions
- How do we decided whether to include the pause image in rootfs? Always, or triggered in the same way as image offload in https://github.com/kata-containers/kata-containers/issues/8103

## Acceptance Criteria

I don't think there are any new tests for this, just that the performance of the current image pull on guest tests should be slightly faster.

**Comment by fitzthum** [comment]
There is a security consideration here. I believe that today even when we pull the pause image inside the guest, it is still mounted to the host. This is a problem because if a host overwrites the pause binary they could execute arbitrary code inside the workload. This might not seem that bad because the binary is running inside a container, but this does expose the network namespace. For example, a host could overwrite the pause binary with a program that queries the CDH for secrets and then exposes them.

When we add the pause container support to main, we need to make sure that there is no way for the host to supply or modify the pause image. No matter what configuration we are running, the pause container should always come from the rootfs (which is measured or otherwise protected).

**Comment by ariel-adam** [comment]
@stevenhorsman @ChengyuZhu6 should this also be tagged is a high-priority issue?

**Comment by stevenhorsman** [comment]
Yes, that's fine, or as Chengyu is implementing it as part of #8484 we could close it as merged into #8103?

**Comment by ariel-adam** [comment]
For now tagging it as high priority and will let you guys decide if you want to also close it

**Comment by stevenhorsman** [comment]
For clarity I'll close this now as covered by #8103 as PRs associated with that work include this change
