### ISSUE TITLE
genpolicy: broken for `ubuntu:latest`

### ISSUE THREAD

**Issue by katexochen** [kata-containers/kata-containers#8574]
# Description of problem

`genpolicy` tool fails when generating a policy for the ubuntu:latest image

```
$ cat test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: ubuntu:latest
```
```
$ genpolicy -y test.yml
thread 'main' panicked at src/registry.rs:111:17:
Failed to pull container image manifest and config - error: UnsupportedMediaTypeError(
    "application/vnd.oci.image.index.v1+json",
)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

# Expected result

Successful generation of a policy.

# Actual result

Tool panicked.

# Further information

See previous discussion in https://github.com/kata-containers/kata-containers/pull/8248#issuecomment-18397125618

**Comment by ChengyuZhu6** [comment]
The issue was related to the manifest type. The registry returned a manifest with the mediatype `application/vnd.oci.image.manifest.v1+json` when pulling ubuntu, which we did not handle properly. This issue has been fixed in the pull request [krustlet/oci-distribution#67]. Therefore, the issue would be resolved once @danmihai1 updates the oci-distribution repo.

**Comment by danmihai1** [comment]
@katexochen @ChengyuZhu6 I have just added @Redent0r's commit to fix this, in https://github.com/kata-containers/kata-containers/pull/8248/commits

**Comment by danmihai1** [comment]
Fixed in the initial genpolicy PR.
