### ISSUE TITLE
genpolicy: broken for `nixery.dev/shell/socat`

### ISSUE THREAD

**Issue by katexochen** [kata-containers/kata-containers#8575]
# Description of problem

`genpolicy` tool fails when generating a policy for the `nixery.dev/shell/socat` image

```
$ cat test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: nixery.dev/shell/socat
```
```
$ genpolicy -y test.yml
thread 'main' panicked at src/registry.rs:91:61:
called `Result::unwrap()` on an `Err` value: Error("missing field `Env`", line: 1, column: 969)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Expected result

Successful generation of a policy.

# Actual result

Tool panicked.

# Further information

See previous discussion in https://github.com/kata-containers/kata-containers/pull/8248#issuecomment-18397125618

**Comment by burgerdev** [comment]
Root cause of this is that nixery.dev produces non-conformant image configs.

```
> crane blob nixery.dev/shell/socat@sha256:06479a95f1b24d0f934b8cdc18d89bdc8c89339774d83de13d126cae966a9be0 | jq '.config'
{
  "cmd": [
    "bash"
  ],
  "env": [
    "SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt"
  ]
}
```

`cmd` and `env` should be `Cmd` and `Env`, respectively ([spec](https://github.com/moby/moby/blob/f417435e5f6216828dec57958c490c4f8bae4f98/image/spec/spec.md?plain=1#L130)). 

I guess nobody noticed so far because in Golang, which almost all container tools seem to be written in, case-insensitive matches unmarshal just fine: https://pkg.go.dev/encoding/json#Unmarshal.

On the bright side, this surfaced a bug in genpolicy: this image should probably still be accepted by genpolicy, and treated as if the `Env` were empty - `ImageConfig.Env` can be omitted according to spec [1] [2], but it's mandatory here:

https://github.com/kata-containers/kata-containers/blob/00be9ae8725f25a9b32e48a9d11fa901fc997b43/src/tools/genpolicy/src/registry.rs#L39-L48

[1]: https://github.com/opencontainers/image-spec/blob/365fa41472a19107b0b4cbc17e141a9b97f9b66e/config.md?plain=1#L152
[2]: https://github.com/krustlet/oci-distribution/blob/4c80c9ca309c8aabab3f1404b3b0e0642b2201c4/src/config.rs#L203-L204
