### ISSUE TITLE
CC: Integrate pause image into rootfs

### ISSUE THREAD

**Issue by ChengyuZhu6** [kata-containers/kata-containers#9032]
**Which feature do you think can be improved?**

For Confidential containers stack, the pause image is managed by host side, then it may configure a malicious pause image, we need package a pause image inside the rootfs and don't the pause image from host. So the pause image will be part of the Kata Containers rootfs that's used by the Confidential Containers usecase.

**Comment by danmihai1** [comment]
I hope there is an option to keep some of these components out of the Guest rootfs. 

Updating the Guest rootfs is expensive in a Production environment so ideally the pause container, the Attestation client, etc. should be pulled from a container image repository rather than cramming all of them into the Guest rootfs.
