### ISSUE TITLE
Deploy the Confidential Containers KBS as part of the confidential tests

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#9056]
Once we start test the attestation workflow we'll need to have a KBS deployed.  As part of the Confidential Containers CI meeting we went through the options we have to do so (docker compose, kbs-operator, and a "simple pod"), and considering the non-TEE tests are running on a node that we don't log in to it, we've decided to take the "simple pod" approach, according to the following documentation: https://github.com/confidential-containers/kbs/tree/main/kbs/config/kubernetes.  There's also a slack thread discussing the topic: https://cloud-native.slack.com/archives/C066XLCU95Z/p1707328323281699

In general, we'll need to:
* Expand the github action to deploy the KBS
* Expand the install script to deploy the KBS
* Populate the KBS with the values we need
* Profit!

I'm creating this issue, but @fitzthum is the best person to actually expand this issue and add more details to it.

**Comment by fitzthum** [comment]
I'll make a few notes here, but refer to the slack thread linked above if you want the most up-to-date info.

@wainersm has a [great branch](https://github.com/wainersm/kata-containers/tree/ci_install_kbs) with a lot of the KBS enablement stuff already sorted out.

It turns out that there is already [support in the KBS](https://github.com/confidential-containers/kbs/tree/main/kbs/config/kubernetes) for deploying with Kubernetes (without the operator). It is somewhat hidden in the config section.

We will also be cutting a v0.8.1 release of the KBS to help with this. I just want to make sure we don't discover any bugs during the process before doing that.

Also, worth noting that CAA CI is working on something [kind of similar](https://github.com/confidential-containers/cloud-api-adaptor/pull/1684)

**Comment by kartikjoshi21** [comment]
> I'll make a few notes here, but refer to the slack thread linked above if you want the most up-to-date info.
> 
> @wainersm has a [great branch](https://github.com/wainersm/kata-containers/tree/ci_install_kbs) with a lot of the KBS enablement stuff already sorted out.
> 
> It turns out that there is already [support in the KBS](https://github.com/confidential-containers/kbs/tree/main/kbs/config/kubernetes) for deploying with Kubernetes (without the operator). It is somewhat hidden in the config section.
> 
> We will also be cutting a v0.8.1 release of the KBS to help with this. I just want to make sure we don't discover any bugs during the process before doing that.
> 
> Also, worth noting that CAA CI is working on something [kind of similar](https://github.com/confidential-containers/cloud-api-adaptor/pull/1684)

Yess, we are adding support to deploy kbs in CI in e2e test and later on we will add tests related to kbs and caa in e2e-test. Also there is a  [PR](https://github.com/confidential-containers/cloud-api-adaptor/pull/1518) already in review for adding support to deploy kbs along with CAA using provisioner

**Comment by fitzthum** [comment]
Btw @kartikjoshi21 I am planning to cut a release of the KBS tomorrow. If you find any issues that could benefit from a last-minute fix, please lmk asap.

**Comment by wainersm** [comment]
> @fitzthum, @wainersm, is there any chance that one of you could do this work?

I am working on this already @fidencio

**Comment by wainersm** [comment]
> Btw @kartikjoshi21 I am planning to cut a release of the KBS tomorrow. If you find any issues that could benefit from a last-minute fix, please lmk asap.

Don't know if you cut the release yet or not, but just to let you know that it is feasible to pin to a commit SHA instead.

**Comment by fitzthum** [comment]
We are overdo a release anyway. We've put in some major fixes since v0.8.0. New version should be live soon. It will have the Kustomize pointing to the KBS image from the new release (which is basically the same as the image your pinned to).

It's handy to have the commit SHA functionality, especially in the short run where we might need a few tweaks but in the longterm we probably want to stick with the releases.
