### ISSUE TITLE
 Add a test for the guest components integration

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#9057]
First of all, I'm assuming the test will come, and will come either disabled or as part of the https://github.com/kata-containers/kata-containers/pull/8870, which is bringing in the code for this.

During the Confidential Containers meeting we discussed that the test will be based on https://github.com/stevenhorsman/kata-containers/commit/3be7d24b8a846112e12f9c2aa1ad53c131467557.

The code gives us an idea on what we'll do, but we still need to find a way to actually figure out, through the logs, that the key is being used.

The basic idea of the test case is to run and config a KBS and use a test pod workload to get a resource using the api-server-rest component. This should provide an end-to-end test to ensure that the attestation components are running, configured and able to talk to a 'remote' KBS.
We also want to have a negative test e.g. that checks that if the KBS policy is set to block, or the KBS URI provided is wrong then we don't get the key back from the ASR

I'm assuming that @stevenhorsman and @fitzthum can add more details to this, if needed.

I'm assigning the issue to Gaby, Steve, and Tobin, but Gaby is the one who'll be working on this with the help of Steve and Tobin.

**Comment by fitzthum** [comment]
A note on the negative tests: 

The default policy blocks the sample evidence but it will release any resources for any other valid evidence. As in, if you make a request from inside some TEE, as long as the evidence is formatted/signed correctly, you can get a resource. In production you should specify an attestation policy that requires the evidence to have certain claims (i.e. a particular launch measurement), but the default policy does not do this.

Basically what this means is that the negative test will look a bit different for the non-tee and tee cases. In the non-tee case the negative test can use the default policy of the KBS. In the TEE cases the negative test will need to specify a new, more restrictive policy.

To start with, we should probably make the negative policy as simple as possible i.e. block everything. In the future we will probably want additional tests that actually check the TCB claims. Calculating the expected claims is probably a little beyond the scope of this, though.

There are some very simple example policies [here](https://github.com/confidential-containers/kbs/tree/main/kbs/test/data). To be clear, the [client tool](https://github.com/confidential-containers/kbs/tree/main/kbs/tools/client), which we will use to set the policies, has an option to set the resource-policy and the attestation-policy. For now we only care about the resource-policy.

**Comment by wainersm** [comment]
@fitzthum @GabyCT

On https://github.com/kata-containers/kata-containers/pull/9065  the KBS service isn't exposed externally, i.e., it is reachable only within the cluster. I will need to change that to publicly expose the service depending on how we will use the kbs client tool on the tests to set policies. So I'd like to have that discussion started.

I can think it will either run the kbs client from:

 1. The Github runner host. 
 2. A Pod within the cluster

Case 1) 

It will be needed to public expose the kbs service. There is already an [Ingress deployment](https://github.com/confidential-containers/kbs/blob/main/kbs/config/kubernetes/overlays/ingress.yaml) and [instructions](https://github.com/confidential-containers/kbs/tree/main/kbs/config/kubernetes#optional-expose-kbs-using-ingress) for when deployed on AKS. However I don't know how tricky it can be even on AKS, let alone other type of clusters (e.g. k3s) that we have used on CI.

Apart from that, the kbs client should be compiled and installed. I'm concerned about the former because it depends on libraries not provided by the distro (Ubuntu), for example, `libtdx-attest-dev`. There will be more software to get installed and managed on the host, but doable I think.

Case 2)

No need to expose the service. Like in the ["healthy checker" in my PR](https://github.com/kata-containers/kata-containers/pull/9065/commits/db45787f3ced351da335ec3ccfe6f158e45c22dc#diff-4f8faef8364fb11204bacf2d8d1467792a861b4d4525e0c533d0dba9278087c0R94) a regular pod running on the same cluster will have access to the service API.

If we manage to compile the client within an image and distribute just like we do for the kbs one then it will save a lot of problems on kata side. One concern would be to share the authentication key within the image, the same key used to deploy the kbs service.

Case N)

There should exist alternatives. For example, not use the kbs client at all, instead use curl/wget to talk to the REST API directly. Any other idea?

**Comment by fitzthum** [comment]
I don't have a strong preference here.

Regarding building the kbs-client. I attached a kbs-client binary to the v0.8.2 release. I'm not sure how convenient it is to pull this kind of binary and I'm not sure how portable the binary is so this is WIP, but in theory we can provide some kind of binary with the release which might help.

Another option is to add some features to the client tool so that we can build without some of the more annoying dependencies. The tool really only requires weird stuff when it is getting a resource (because it will try to do an attestation). We should only need the config endpoints for the tests.

For the second case, if we put the client tool in the cluster, we'll probably still need to communicate with it from the runner unless all of the testing logic moves to the pod (not sure this is possible). So I guess I lean a bit more towards the first case although I don't know exactly what goes into exposing the service.

**Comment by wainersm** [comment]
> I don't have a strong preference here.
> 
> Regarding building the kbs-client. I attached a kbs-client binary to the v0.8.2 release. I'm not sure how convenient it is to pull this kind of binary and I'm not sure how portable the binary is so this is WIP, but in theory we can provide some kind of binary with the release which might help.
>

It would be super convenient to download a static compiled binary of kbs-client. One caveat is when it needs to check-out the code from a given commit SHA1, in this case it will need to compile the client anyway. 
 
> Another option is to add some features to the client tool so that we can build without some of the more annoying dependencies. The tool really only requires weird stuff when it is getting a resource (because it will try to do an attestation). We should only need the config endpoints for the tests.
> 

I figured I can compile the client with `sample_only` feature. I didn't check what dependencies does it requires, I hope it can do the trick.

> For the second case, if we put the client tool in the cluster, we'll probably still need to communicate with it from the runner unless all of the testing logic moves to the pod (not sure this is possible). So I guess I lean a bit more towards the first case although I don't know exactly what goes into exposing the service.

I will change https://github.com/kata-containers/kata-containers/pull/9065 to expose the KBS service and install the client locally. Let's see what problems (if any) I will face with the second case.
