### ISSUE TITLE
Select CI jobs by touched code/files

### ISSUE THREAD

**Issue by ldoktor** [kata-containers/kata-containers#9237]
**Is your feature request related to a problem? Please describe.**

The kata-containers repo contains many CI tests (GH actions...) but some tests are really targeted to specific features only. Still all the tests are run all the times in PR, which results in quite a big machine as well as human overhead especially because of flaky tests.

**Describe the solution you'd like**

I'd like to identify at least some relations between directories/files (eg. `docs/`, `ci/`, `tools/testing/`) and tests (docs only, functional, unittest, ...). Then we can filter the tests that can be skipped/not executed in case only specific locations are touched by the PR.

This should **not** influence the post-merge set of tests as we do want to always run the full set on merge.

**Describe alternatives you've considered**

* GH path filter - rejected previously as required tests will not be reported
* GH path filter + fake tests with the same names as the required ones (might work)
* Custom solution (script?) to report PASS for set of tests when:
  * certain location(s) is/are touched - potentially dangerous as might result in untested code (within PR, post-merge should test everything)
  * unless only certain location(s) is/are touched - safer but the inverted logic might not look as smooth

CC: @wainersm

**Comment by stevenhorsman** [comment]
I like this idea - as we discussed on the AC call, we tried something similar with path filters and that didn't work, so we need the check at the tests level. 

We also need to ensure that we don't accidentally skip too much, so design it to default to run all tests and then exclude only based on specific rules, rather than it being opt-in based on file paths as these might change and result in things falling through the cracks.
